# Generated by Django 4.0.4 on 2022-06-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_two', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='e_mail',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='name@email.com', max_length=64, unique=True),
        ),
    ]
